### vehicles#index
GET http://127.0.0.1:3000/api/v1/vehicles

### vehicles#create
POST http://127.0.0.1:3000/api/v1/vehicles HTTP/1.1
Accept: application/json
Content-Type: application/json

{"vehicle": {
    "name":"vehicle name",
     "image":"image link"
    }
}

### vehicles#show
GET http://127.0.0.1:3000/api/v1/vehicles/:id

### Vehicles#destroy
DELETE http://127.0.0.1:3000/api/v1/vehicles/:id


### reservations#index
GET http://127.0.0.1:3000/api/v1/reservations HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "user_id": 2
}
### This also works:
GET http://127.0.0.1:3000/api/v1/reservations?user_id=1 
### reservations#create
POST http://127.0.0.1:3000/api/v1/reservations HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "reservation": {
        "reserve_date":"2023-01-21 11:00",
        "address":"Tokyo, Japan request htttp example",
        "user_id": 1,
        "vehicle_id": 1
    }
}

### reservations#destroy
DELETE http://127.0.0.1:3000/api/v1/reservations/:id
